### ISSUE TITLE
Can only do one generate

### ISSUE THREAD

**Issue by timfpark** [evanlouie/fabrikate-istio#4]
An operator that wants to do deployments into multiple clusters will run `fab generate <env>` multiple times in their CI/CD pipeline, but currently the component is deleting tmp after the first generate, necessitating a second `install`.  Is there a reason we have to delete `tmp` after the first generate and can't retain it for subsequent `generate`s?

(See https://github.com/timfpark/fabrikate-multicluster-multideployment for more context.)

**Comment by evanlouie** [comment]
Resolved. no longer `rm`ing the tmp folder.
